apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    serving.kserve.io/autoscalerClass: none
    serving.kserve.io/deploymentMode: RawDeployment
    networking.kserve.io/visibility: exposed
    opendatahub.io/dashboard: 'true'
    opendatahub.io/genai-asset: 'true'
  name: qwen25-7b-multinode
spec:
  predictor:
    automountServiceAccountToken: false
    model:
      modelFormat:
        name: vLLM
      name: ''
      args:
        - '--tool-call-parser=hermes'
        - '--enable-auto-tool-choice'
        - '--max-model-len=10000'
      runtime: vllm-multinode-runtime
      storageUri: 'pvc://model-storage/Qwen/Qwen2.5-7B-Instruct'
      resources:
        limits:
          cpu: '6'
          memory: 16Gi
        requests:
          cpu: '4'
          memory: 8Gi
    nodeSelector:
      node.kubernetes.io/instance-type: g6.2xlarge
 
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        value: "true"
    workerSpec:
      pipelineParallelSize: 2
      tensorParallelSize: 1