apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  name: qwen25-7b-llmd
spec:
  model:
    uri: pvc://model-storage/Qwen/Qwen2.5-7B-Instruct
    name: Qwen2.5-7B-Instruct
  # Three replicas for load balancing
  replicas: 3
  router:
    scheduler: { }  # Default scheduler with default load balancing
    route: { }
    gateway: { }
  template:
    containers:
      - name: main
        resources:
          limits:
            cpu: '4'
            memory: 16Gi
            nvidia.com/gpu: "1"
          requests:
            cpu: '2'
            memory: 16Gi
            nvidia.com/gpu: "1"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
            scheme: HTTPS
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 30
          failureThreshold: 5